#!/bin/sh

export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export OF_SCREEN_H=1600
export OF_STATUS_H=50
export OF_STATUS_INDENT_LEFT=48
export OF_STATUS_INDENT_RIGHT=48
export OF_CLOCK_POS=1
export OF_ALLOW_DISABLE_NAVBAR=0
export FOX_DELETE_AROMAFM=1
export FOX_BUILD_TYPE="Beta"
export FOX_REMOVE_BASH=1
export OF_MAINTAINER=nanerbs25
export OF_STATUS_INDENT_LEFT=48
export FOX_REMOVE_AAPT-1
